name: Playwright CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run tests (chromium, firefox, webkit, all)'
        required: false
        default: all
  schedule:
    - cron: '0 2 * * *' # Daily at 2 AM UTC

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, firefox, webkit] # Multi-browser matrix

    steps:
      # 1️⃣ Checkout repository
      - name: 1️⃣ Checkout code
        uses: actions/checkout@v4
        # Pulls repo code for tests

      # 2️⃣ Setup Node.js
      - name: 2️⃣ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
        # Node 18 ensures maximum compatibility

      # 3️⃣ Cache npm dependencies
      - name: 3️⃣ Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        # Speeds up CI by caching dependencies

      # 4️⃣ Install project dependencies
      - name: 4️⃣ Install dependencies
        run: npm ci
        # Installs project dependencies

      # 5️⃣ Install system dependencies for Playwright (Ubuntu 24.04)
      - name: 5️⃣ Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libnss3 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libdrm2 \
            libxkbcommon0 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libgbm1 \
            libpangocairo-1.0-0 \
            libgtk-3-0 \
            libxshmfence1 \
            libx11-xcb1 \
            libxrender1 \
            libexpat1 \
            libpango-1.0-0
        # Installs required system libraries for browsers

      # 6️⃣ Cache Playwright Browsers
      - name: 6️⃣ Cache Playwright Browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-browsers
        # Speeds up CI by caching downloaded browsers

      # 7️⃣ Install Playwright Browsers
      - name: 7️⃣ Install Playwright Browsers
        run: |
          echo "Installing Playwright browsers with dependencies..."
          npx playwright install --with-deps chromium firefox webkit --verbose
        # Ensures all browsers installed reliably

      # 8️⃣ Generate Test Plan (Planner)
      - name: 8️⃣ Generate Test Plan (Planner)
        run: |
          echo "Generating AI test plan..."
          npx @playwright/ai planner --url https://example.com --output ./plan.md
        # Creates structured AI-generated test plan

      # 9️⃣ Generate Tests from Plan (Generator)
      - name: 9️⃣ Generate Tests (Generator)
        run: |
          echo "Generating Playwright tests from plan..."
          npx @playwright/ai generator --plan ./plan.md --output ./tests
        # Converts plan into runnable Playwright tests

      # 🔟 Run Playwright Tests
      - name: 🔟 Run Playwright Tests
        run: |
          echo "Running tests..."
          if [ "${{ github.event.inputs.browser }}" != "" ] && [ "${{ github.event.inputs.browser }}" != "all" ]; then
            npx playwright test ./tests --browser ${{ github.event.inputs.browser }} --reporter=html --retries=2 --workers=2
          else
            npx playwright test ./tests --reporter=html --retries=2 --workers=2
        # Executes tests with retries, parallel execution, and browser selection

      # 1️⃣1️⃣ Heal Failing Tests (Healer)
      - name: 1️⃣1️⃣ Heal Failing Tests (Healer)
        run: |
          echo "Healing failing tests..."
          npx @playwright/ai healer --tests ./tests --retries 2
        # Automatically repairs failing tests

      # 1️⃣2️⃣ Upload HTML Report
      - name: 1️⃣2️⃣ Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report
        # Uploads test report for review
