name: Playwright CI/CD

# Workflow triggers
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run tests (chromium, firefox, webkit)'
        required: false
        default: all
  schedule:
    - cron: '0 2 * * *' # Runs every day at 2 AM UTC

# Define jobs
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Cache npm dependencies
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 5️⃣ Install Playwright browsers & dependencies
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # 6️⃣ Run Playwright tests
      - name: Run Playwright Tests
        run: |
          if [ "${{ github.event.inputs.browser }}" != "" ] && [ "${{ github.event.inputs.browser }}" != "all" ]; then
            npx playwright test --browser ${{ github.event.inputs.browser }} --reporter=html --retries=2
          else
            npx playwright test --reporter=html --retries=2
          fi

      # 7️⃣ Upload HTML report
      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-html-report
          path: playwright-report

      # 8️⃣ Optional: Run Playwright Agents (Planner / Generator / Healer)
      - name: Run Playwright Agents (Optional)
        if: ${{ github.event.inputs.browser == '' || github.event.inputs.browser == 'all' }}
        run: |
          echo "This is where you would integrate AI agents if configured."
          # npx @playwright/agent planner
          # npx @playwright/agent generator
          # npx @playwright/agent healer
